# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sem_likelihood_calculate <- function(alpha, phi_0, err_var, dep_vars, Y1, Y2, cur_Z, cur_Y2 = NULL, beta = NULL, phi_1 = NULL, phis = NULL, psis = NULL, per_entity = FALSE, exact_value = TRUE) {
    .Call(`_badp_sem_likelihood_calculate`, alpha, phi_0, err_var, dep_vars, Y1, Y2, cur_Z, cur_Y2, beta, phi_1, phis, psis, per_entity, exact_value)
}

#' Residual Maker Matrix
#'
#' Create residual maker matrix from a given matrix \code{m}. See article about
#' \href{https://en.wikipedia.org/wiki/Projection_matrix}{projection matrix} on
#' the Wikipedia.
#'
#' @param m Matrix
#'
#' @return
#' M x M matrix where M is the number of rows in the \code{m} matrix.
#' @export
#'
#' @examples
#' residual_maker_matrix(matrix(c(1,2,3,4), nrow = 2))
#'
#' @keywords internal
residual_maker_matrix <- function(m) {
    .Call(`_badp_residual_maker_matrix`, m)
}

#' Coefficients matrix for SEM representation
#'
#' Create coefficients matrix for Simultaneous Equations Model (SEM)
#' representation.
#'
#' @param alpha numeric
#' @param n_periods integer
#' @param beta numeric vector. Default is c() for no regressors case.
#'
#' @return List with two matrices B11 and B12
#' @export
#'
#' @examples
#' sem_B_matrix(3, 4, 4:6)
#'
#' @keywords internal
sem_B_matrix <- function(alpha, n_periods, beta = NULL) {
    .Call(`_badp_sem_B_matrix`, alpha, n_periods, beta)
}

#' Coefficients matrix for initial conditions
#'
#' Create matrix for Simultaneous Equations Model (SEM)
#' representation with coefficients placed next to initial values
#' of regressors, dependent variable and country-specific time-invariant
#' variables.
#'
#' @param alpha numeric
#' @param phi_0 numeric
#' @param n_periods numeric
#' @param beta numeric vector. Default is c() for no regressors case.
#' @param phi_1 numeric vector. Default is c() for no regressors case.
#'
#' @return matrix
#' @export
#'
#' @examples
#' alpha <- 9
#' phi_0 <- 19
#' beta <- 11:15
#' phi_1 <- 21:25
#' n_periods <- 4
#' sem_C_matrix(alpha, phi_0, n_periods, beta, phi_1)
#'
#' @keywords internal
sem_C_matrix <- function(alpha, phi_0, n_periods, beta = NULL, phi_1 = NULL) {
    .Call(`_badp_sem_C_matrix`, alpha, phi_0, n_periods, beta, phi_1)
}

#' Matrix with psi parameters for SEM representation
#'
#' @param psis double vector with psi parameter values
#' @param n_timestamps number of time stamps (e.g. years)
#' @param n_features number of features (e.g. population size, investment rate)
#'
#' @return
#' A matrix with \code{n_timestamps} rows and
#' \code{(n_timestamps - 1) * n_features} columns. Psis are filled in row by row
#' in a block manner, i.e. blocks of size \code{n_features} are placed next to
#' each other
#'
#' @export
#'
#' @examples
#' sem_psi_matrix(1:30, 4, 5)
#'
#' @keywords internal
sem_psi_matrix <- function(psis, n_timestamps, n_features) {
    .Call(`_badp_sem_psi_matrix`, psis, n_timestamps, n_features)
}

#' Covariance matrix for SEM representation
#'
#' Create covariance matrix for Simultaneous Equations Model (SEM)
#' representation. Only the part necessary to compute concentrated likelihood
#' function is computed (cf. Appendix in the Moral-Benito paper)
#'
#' @param err_var numeric
#' @param dep_vars numeric vector
#' @param phis numeric vector
#' @param psis numeric vector
#'
#' @return List with two matrices Sigma11 and Sigma12
#' @export
#'
#' @examples
#' err_var <- 1
#' dep_vars <- c(2, 2, 2, 2)
#' phis <- c(10, 10, 20, 20, 30, 30)
#' psis <- c(101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112)
#' sem_sigma_matrix(err_var, dep_vars, phis, psis)
#'
#' @keywords internal
sem_sigma_matrix <- function(err_var, dep_vars, phis = NULL, psis = NULL) {
    .Call(`_badp_sem_sigma_matrix`, err_var, dep_vars, phis, psis)
}

